name: Deploy to GitHub Pages

on:
  push:
    branches:
      - feat/image-to-3d-converter  # o la rama que uses para producción

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Combine model files
        run: |
          mkdir -p assets
          cat assets/midas.tflite.part_* > assets/midas.tflite
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
          clean: true
