name: Deploy to GitHub Pages

on:
  push:
    branches:
      - feat/image-to-3d-converter

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Combine model files
        run: |
          mkdir -p assets
          cat assets/midas.tflite.part_* > assets/midas.tflite
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "."
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
